export const ActionTypes = {
    CLEAN_STATE:"CLEAN_STATE",
  
    LOGIN_USER_START: "LOGIN_USER_START",
    LOGIN_USER_SUCCESS: "LOGIN_USER_SUCCESS",
    LOGIN_USER_FAILURE: "LOGIN_USER_FAILURE",
  
    SIGNUP_USER_START: "SIGNUP_USER_START",
    SIGNUP_USER_SUCCESS: "SIGNUP_USER_SUCCESS",
    SIGNUP_USER_FAILURE: "SIGNUP_USER_FAILURE",
  
    LOGOUT_START: "LOGOUT_START",
    LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
    LOGOUT_FAILURE: "LOGOUT_FAILURE",

    REGISTER_PATIENT_START:"REGISTER_PATIENT_START",
    REGISTER_PATIENT_SUCCESS:"REGSITER_PATIENT_SUCCESS",
    REGISTER_PATIENT_FAILURE:"REGISTER_PATIENT_FAILURE",
    
    GET_PATIENT_START: "GET_PATIENT_START",
    GET_PATIENT_SUCCESS: "GET_PATIENT_SUCCESS",
    GET_PATIENT_FAILURE: "GET_PATIENT_FAILURE",

    TODAY_CHALLENGE_COMPLETE_START: "TODAY_CHALLENGE_COMPLETE_START",
    TODAY_CHALLENGE_COMPLETE_SUCCESS: "TODAY_CHALLENGE_COMPLETE_SUCCESS",
    TODAY_CHALLENGE_COMPLETE_FAILURE: "TODAY_CHALLENGE_COMPLETE_FAILURE",


  };
  